BEGIN;

INSERT INTO public.chat_event_rule (
  route_key,
  rule_key,
  intent_key,
  pattern_regex,
  filters_template,
  parse_date_range,
  parse_period,
  parse_severity,
  parse_func,
  parse_status,
  fallback_keyword,
  enabled,
  priority,
  confidence,
  created_at,
  updated_at
)
VALUES
  (
    'robot/ailog/event',
    'issue-today',
    'ailog-event-query',
    '(오늘).*(이슈|이벤트)|(이슈|이벤트).*(오늘)',
    '{}'::jsonb,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    1000,
    0.99,
    NOW(),
    NOW()
  ),
  (
    'robot/ailog/event',
    'issue-yesterday',
    'ailog-event-query',
    '(어제).*(이슈|이벤트)|(이슈|이벤트).*(어제)',
    '{}'::jsonb,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    990,
    0.99,
    NOW(),
    NOW()
  ),
  (
    'robot/ailog/event',
    'issue-date-range',
    'ailog-event-query',
    '(\d{4}[./-]\d{1,2}[./-]\d{1,2}|\d{1,2}\s*월\s*\d{1,2}\s*일).*(부터|까지|~|to|에서).*(\d{4}[./-]\d{1,2}[./-]\d{1,2}|\d{1,2}\s*월\s*\d{1,2}\s*일|\d{1,2}\s*일).*(이슈|이벤트)',
    '{}'::jsonb,
    true,
    false,
    true,
    true,
    true,
    true,
    true,
    980,
    0.97,
    NOW(),
    NOW()
  ),
  (
    'robot/ailog/event',
    'issue-function',
    'ailog-event-query',
    '([^\s,]+)\s*기능.*(이슈|이벤트)|(이슈|이벤트).*(기능)',
    '{}'::jsonb,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    970,
    0.96,
    NOW(),
    NOW()
  ),
  (
    'robot/ailog/event',
    'issue-severity-status',
    'ailog-event-query',
    '(critical|high|medium|middle|low|치명|심각|높음|중간|낮음|received|prepared|prepare_failed|analyzing|analyzed|analyze_failed|completed|failed|로그획득|분석준비완료|분석준비실패|분석중|분석완료|분석실패|조치완료|오류발생).*(이슈|이벤트)|(이슈|이벤트).*(critical|high|medium|middle|low|치명|심각|높음|중간|낮음|received|prepared|prepare_failed|analyzing|analyzed|analyze_failed|completed|failed|로그획득|분석준비완료|분석준비실패|분석중|분석완료|분석실패|조치완료|오류발생)',
    '{}'::jsonb,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    960,
    0.95,
    NOW(),
    NOW()
  ),
  (
    'robot/ailog/event',
    'issue-generic-fallback',
    'ailog-event-query',
    '(이슈|이벤트)',
    '{}'::jsonb,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    900,
    0.9,
    NOW(),
    NOW()
  )
ON CONFLICT (route_key, rule_key)
DO UPDATE SET
  intent_key = EXCLUDED.intent_key,
  pattern_regex = EXCLUDED.pattern_regex,
  filters_template = EXCLUDED.filters_template,
  parse_date_range = EXCLUDED.parse_date_range,
  parse_period = EXCLUDED.parse_period,
  parse_severity = EXCLUDED.parse_severity,
  parse_func = EXCLUDED.parse_func,
  parse_status = EXCLUDED.parse_status,
  fallback_keyword = EXCLUDED.fallback_keyword,
  enabled = EXCLUDED.enabled,
  priority = EXCLUDED.priority,
  confidence = EXCLUDED.confidence,
  updated_at = NOW();

COMMIT;
