export const CAMPAIGN_STATUS = {
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELED: 'CANCELED',
  DELETION_IN_PROGRESS: 'DELETION_IN_PROGRESS'
}

export const DEPLOYMENT_STATUS = {
  QUEUED: 'QUEUED',
  IN_PROGRESS: 'IN_PROGRESS',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  TIMED_OUT: 'TIMED_OUT',
  REJECTED: 'REJECTED',
  REMOVED: 'REMOVED',
  CANCELED: 'CANCELED'
}
